### ISSUE TITLE
wrong collection name in the word document

### ISSUE THREAD

**Issue by emredipi** [DevFest-India/devfest-india-manage-2020#1]
Hi, I am Emre from GDG Sivas. We just build our devfestturkey site thanks to your template. When we try to give permission to our accounts to manage template we have noticed that, your firebase rules are using 'admins' collection but your word document says that we need to add uid to 'users' collection. Can you update that? Thanks again.

**Comment by vrijraj** [comment]
Hi @emredipi 

it will be "admins" as collection name. I have updated the doc. 
You have to customize the components accordingly.

**Comment by vrijraj** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/10599101/92858316-8ae46000-f413-11ea-825a-8c8b950f580c.png)
